version: '3.8'

services:

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - .env
    command: server /data --console-address ":9002"   # фиксируем WebUI порт
    ports:
      - "9001:9000"  # API
      - "9002:9002"  # Web
    volumes:
      - minio_data:/data
    networks:
      - ml-network


  jupyter:
    build:
      context: .
      dockerfile: services/jupyter/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - mlflow_tmp:/tmp/mlflow
    command: >
      start-notebook.sh
      --NotebookApp.token=''
      --NotebookApp.password=''
      --NotebookApp.allow_origin='*'
      --NotebookApp.allow_remote_access=True
    networks:
      - ml-network
    env_file:
      - .env


  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - mlflow_tmp:/tmp/mlflow
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - ml-network
    env_file:
      - .env

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./infra/clickhouse:/docker-entrypoint-initdb.d

    networks:
      - ml-network      
    env_file:
    - .env
      

  airflow-init:
    build:
      context: .
      dockerfile: services/airflow/Dockerfile
    depends_on:
      - postgres
    environment:
      _PIP_ADDITIONAL_REQUIREMENTS: >
        mlflow
        scikit-learn
        pandas
        numpy
        pandahouse
    env_file:
    - .env
      
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    networks:
      - ml-network


  airflow-scheduler:
    build:
      context: .
      dockerfile: services/airflow/Dockerfile
    command: airflow scheduler
    environment:
      PYTHONPATH: /opt/airflow
    env_file:
      - .env
    depends_on:
      - airflow-init
      - clickhouse
    ports:
      - "8794:8794"
    volumes:
      - ./infra/airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src   
      - mlflow_data:/mlflow
    networks:
      - ml-network

  airflow-webserver:
    build:
      context: .
      dockerfile: services/airflow/Dockerfile
    command: airflow webserver
    ports:
      - "8080:8080"
    environment:
      PYTHONPATH: /opt/airflow
      AIRFLOW__WEBSERVER__RBAC: "True"
      _PIP_ADDITIONAL_REQUIREMENTS: >
        mlflow==1.30.1
        scikit-learn
        pandas
        numpy
        pandahouse

    env_file:
      - .env
    depends_on:
      - airflow-init
    networks:
      - ml-network
    volumes:
      - mlflow_data:/opt/airflow/mlruns
      - ./infra/airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src 


  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - ml-network

  mlflow-server:
    build:
      context: .
      dockerfile: services/mlflow/Dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - minio
    volumes:
      - mlflow_backend:/mlflow/backend
      - mlflow_tmp:/tmp/mlflow
    networks:
      - ml-network
    env_file:
      - .env
    command: >
        mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri postgresql+psycopg2://mlflow:mlflow@postgres:5432/mlflow
        --default-artifact-root s3://mlflow-artifacts
        --registry-store-uri postgresql+psycopg2://mlflow:mlflow@postgres:5432/mlflow
        --allowed-hosts '*'
        --cors-allowed-origins '*'



  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ml-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    env_file:
      - .env
      
    ports:
      - "9092:9092"
    networks:
      - ml-network

  redis:
    image: redis:7.0.8
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ml-network
      

volumes:
  clickhouse_data:
  postgres_data:
  mlflow_data:
  redis_data:
  mlflow_backend:
  mlflow_tmp:
  minio_data:


networks:
  ml-network: